import { useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, Share2, RotateCcw, Home, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ReportCard } from '@/components/ReportCard';
import { ShareModal } from '@/components/ShareModal';
import { XPNotification } from '@/components/XPNotification';
import { SEO } from '@/components/SEO';
import { getResult, getSheet } from '@/lib/storage';
import { recordExamCompletion, getXPProgress, getLevelFromXP } from '@/lib/gamification';
import { updateAdaptiveProfile } from '@/lib/adaptiveEngine';
import { useEffect, useRef } from 'react';

export default function ResultPage() {
  const { attemptId } = useParams<{ attemptId: string }>();
  const navigate = useNavigate();
  const [shareOpen, setShareOpen] = useState(false);
  const [xpOpen, setXpOpen] = useState(false);
  const [xpData, setXpData] = useState<{
    xpEarned: number;
    xpBreakdown: { label: string; xp: number }[];
    newBadges: any[];
    leveledUp: boolean;
    newLevel: number;
    xpProgress: { current: number; needed: number; percent: number };
  } | null>(null);
  const processedRef = useRef(false);
  
  const result = attemptId ? getResult(attemptId) : null;
  const sheet = result ? getSheet(result.sheetId) : null;

  // Process gamification and adaptive learning on first render
  useEffect(() => {
    if (!result || !sheet || processedRef.current) return;
    processedRef.current = true;

    // Check if already processed (simple check via sessionStorage)
    const processedKey = `xp_processed_${attemptId}`;
    if (sessionStorage.getItem(processedKey)) return;
    sessionStorage.setItem(processedKey, 'true');

    // Record gamification
    const gamResult = recordExamCompletion(result.accuracy, result.correct, result.timeSpent, result.totalQuestions);
    
    // Update adaptive profile
    updateAdaptiveProfile(result, sheet.subject || sheet.title);

    setXpData({
      xpEarned: gamResult.xpEarned,
      xpBreakdown: gamResult.xpBreakdown,
      newBadges: gamResult.newBadges,
      leveledUp: gamResult.leveledUp,
      newLevel: gamResult.state.level,
      xpProgress: getXPProgress(gamResult.state.xp),
    });

    // Show XP notification after a short delay
    setTimeout(() => setXpOpen(true), 800);
  }, [result, sheet, attemptId]);

  if (!result || !sheet) {
    return (
      <div className="min-h-screen flex items-center justify-center flex-col gap-4">
        <p className="text-muted-foreground">Result not found</p>
        <Link to="/"><Button>Go Home</Button></Link>
      </div>
    );
  }

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}m ${secs}s`;
  };

  const shareText = `🎯 Exam Master Report Card\n\n📝 ${result.sheetTitle}\n📅 ${result.completedAt.toLocaleDateString()}\n\n📊 RESULTS:\n✅ Score: ${result.score}/${result.maxScore}\n🎯 Accuracy: ${result.accuracy}%\n⏱️ Time: ${formatTime(result.timeSpent)}\n\n📈 BREAKDOWN:\n✓ Correct: ${result.correct}\n✗ Wrong: ${result.wrong}\n○ Unattempted: ${result.unattempted}\n\nGenerated by Exam Master`;

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-card print:hidden">
        <div className="container py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link to="/"><Button variant="ghost" size="icon"><ArrowLeft className="w-5 h-5" /></Button></Link>
              <div>
                <h1 className="text-xl font-semibold">Report Card</h1>
                <p className="text-sm text-muted-foreground">{result.sheetTitle}</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="icon" onClick={() => window.print()}>
                <Printer className="w-4 h-4" />
              </Button>
              <Button variant="outline" size="icon" onClick={() => setShareOpen(true)}>
                <Share2 className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
      </header>

      <main className="container py-8">
        <div className="max-w-4xl mx-auto">
          <ReportCard result={result} sheet={sheet} />

          <div className="flex flex-wrap gap-4 justify-center mt-8 print:hidden">
            <Button variant="outline" className="gap-2" onClick={() => setShareOpen(true)}>
              <Share2 className="w-4 h-4" /> Share Result
            </Button>
            <Button variant="outline" className="gap-2" onClick={() => window.print()}>
              <Printer className="w-4 h-4" /> Print Report
            </Button>
            <Button variant="outline" className="gap-2" onClick={() => navigate(`/exam/${sheet.id}`)}>
              <RotateCcw className="w-4 h-4" /> Retry Exam
            </Button>
            <Link to="/"><Button className="gap-2"><Home className="w-4 h-4" /> Back to Home</Button></Link>
          </div>
        </div>
      </main>

      <ShareModal
        open={shareOpen}
        onOpenChange={setShareOpen}
        data={{
          title: result.sheetTitle,
          text: shareText,
          score: result.score,
          maxScore: result.maxScore,
          accuracy: result.accuracy,
        }}
      />

      {xpData && (
        <XPNotification
          open={xpOpen}
          onOpenChange={setXpOpen}
          xpEarned={xpData.xpEarned}
          xpBreakdown={xpData.xpBreakdown}
          newBadges={xpData.newBadges}
          leveledUp={xpData.leveledUp}
          newLevel={xpData.newLevel}
          xpProgress={xpData.xpProgress}
        />
      )}
    </div>
  );
}
