import { useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, Share2, RotateCcw, Home, Download, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ReportCard } from '@/components/ReportCard';
import { ShareModal } from '@/components/ShareModal';
import { getResult, getSheet } from '@/lib/storage';
import { toast } from 'sonner';

export default function ResultPage() {
  const { attemptId } = useParams<{ attemptId: string }>();
  const navigate = useNavigate();
  
  const result = attemptId ? getResult(attemptId) : null;
  const sheet = result ? getSheet(result.sheetId) : null;

  if (!result || !sheet) {
    return (
      <div className="min-h-screen flex items-center justify-center flex-col gap-4">
        <p className="text-muted-foreground">Result not found</p>
        <Link to="/">
          <Button>Go Home</Button>
        </Link>
      </div>
    );
  }

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}m ${secs}s`;
  };

  const handleShare = () => {
    const text = `🎯 Exam Master Report Card

📝 ${result.sheetTitle}
📅 ${result.completedAt.toLocaleDateString()}

📊 RESULTS:
✅ Score: ${result.score}/${result.maxScore}
🎯 Accuracy: ${result.accuracy}%
⏱️ Time: ${formatTime(result.timeSpent)}

📈 BREAKDOWN:
✓ Correct: ${result.correct}
✗ Wrong: ${result.wrong}
○ Unattempted: ${result.unattempted}

Generated by Exam Master`;
    
    if (navigator.share) {
      navigator.share({ text });
    } else {
      navigator.clipboard.writeText(text);
      toast.success('Report copied to clipboard!');
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleRetry = () => {
    navigate(`/exam/${sheet.id}`);
  };

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-card print:hidden">
        <div className="container py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link to="/">
                <Button variant="ghost" size="icon">
                  <ArrowLeft className="w-5 h-5" />
                </Button>
              </Link>
              <div>
                <h1 className="text-xl font-semibold">Report Card</h1>
                <p className="text-sm text-muted-foreground">{result.sheetTitle}</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="icon" onClick={handlePrint}>
                <Printer className="w-4 h-4" />
              </Button>
              <Button variant="outline" size="icon" onClick={handleShare}>
                <Share2 className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
      </header>

      <main className="container py-8">
        <div className="max-w-4xl mx-auto">
          <ReportCard result={result} sheet={sheet} />

          {/* Actions */}
          <div className="flex flex-wrap gap-4 justify-center mt-8 print:hidden">
            <Button variant="outline" className="gap-2" onClick={handleShare}>
              <Share2 className="w-4 h-4" />
              Share Result
            </Button>
            <Button variant="outline" className="gap-2" onClick={handlePrint}>
              <Printer className="w-4 h-4" />
              Print Report
            </Button>
            <Button variant="outline" className="gap-2" onClick={handleRetry}>
              <RotateCcw className="w-4 h-4" />
              Retry Exam
            </Button>
            <Link to="/">
              <Button className="gap-2">
                <Home className="w-4 h-4" />
                Back to Home
              </Button>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
