import { PublicLayout } from "@/components/PublicLayout";

export default function PrivacyPage() {
  return (
    <PublicLayout>
      <article className="container mx-auto px-4 py-16 max-w-3xl prose-content">
        <p className="text-sm font-semibold text-primary uppercase tracking-wider mb-2">Legal</p>
        <h1 className="text-4xl font-bold font-display tracking-tight">Privacy Policy</h1>
        <p className="text-sm text-muted-foreground mt-2">Last updated: June 12, 2026</p>

        <p className="text-foreground/90 leading-relaxed mt-6">
          This Privacy Policy explains what information Exam Master collects, how we use it, and the
          choices you have. By using Exam Master you agree to the practices described here.
        </p>

        <h2 className="text-2xl font-display font-semibold mt-10 mb-3">Information we collect</h2>
        <ul className="space-y-2 my-4 list-disc list-outside pl-5 text-foreground/90 leading-relaxed">
          <li><strong>Profile details</strong> you provide at sign-up: name, class, school, country, and (optionally) phone number.</li>
          <li><strong>Practice activity</strong> generated by your use of the app: OMR sheets you create, attempts, answers, scores, and time spent.</li>
          <li><strong>Technical data</strong> like device type, browser, IP address (used only for security and abuse-prevention), and aggregate analytics.</li>
          <li><strong>Files you upload</strong> in study groups (notes, PDFs, images) — stored privately and visible only to members of that group.</li>
        </ul>

        <h2 className="text-2xl font-display font-semibold mt-10 mb-3">How we use it</h2>
        <p className="text-foreground/90 leading-relaxed">
          We use your data to power the features you see — generating analytics, suggesting study
          topics, scoring tests, and personalising the dashboard. We do not sell personal data to
          third parties. We do not use student data to train external AI models.
        </p>

        <h2 className="text-2xl font-display font-semibold mt-10 mb-3">Where it lives</h2>
        <p className="text-foreground/90 leading-relaxed">
          Data is stored on Supabase (PostgreSQL) with row-level security: each user can only read
          and write their own rows. Group content (messages, files) is restricted to members of
          that group through enforced policies on the database itself.
        </p>

        <h2 className="text-2xl font-display font-semibold mt-10 mb-3">Cookies and analytics</h2>
        <p className="text-foreground/90 leading-relaxed">
          We use Google Analytics to understand aggregate usage of the site (pages visited, broad
          device categories). Analytics cookies do not identify you personally. If you do not want
          to be tracked, you can disable cookies in your browser or use any standard tracker
          blocker.
        </p>

        <h2 className="text-2xl font-display font-semibold mt-10 mb-3">Advertising</h2>
        <p className="text-foreground/90 leading-relaxed">
          Public marketing pages (the home page, blog articles, about page) may display
          contextually relevant advertisements served by third-party ad networks such as Google
          AdSense. These networks may use cookies to show ads based on your prior visits to this
          and other sites. You can opt out of personalised advertising at{" "}
          <a href="https://www.google.com/settings/ads" className="text-primary hover:underline">
            google.com/settings/ads
          </a>
          . Ads are never shown inside practice, scoring, analytics, or chat screens.
        </p>

        <h2 className="text-2xl font-display font-semibold mt-10 mb-3">Your rights</h2>
        <ul className="space-y-2 my-4 list-disc list-outside pl-5 text-foreground/90 leading-relaxed">
          <li>You can edit your profile at any time from the Profile page.</li>
          <li>You can delete your account by contacting us; we will erase your data within 30 days.</li>
          <li>You can export your practice history on request.</li>
        </ul>

        <h2 className="text-2xl font-display font-semibold mt-10 mb-3">Children</h2>
        <p className="text-foreground/90 leading-relaxed">
          Exam Master is intended for school students of class 6 and above. We do not knowingly
          collect data from children under 13. If you believe we have collected data from a child
          under 13, please contact us and we will remove it.
        </p>

        <h2 className="text-2xl font-display font-semibold mt-10 mb-3">Contact</h2>
        <p className="text-foreground/90 leading-relaxed">
          Questions about this policy? Reach out via the <a href="/contact" className="text-primary hover:underline">contact page</a>.
        </p>
      </article>
    </PublicLayout>
  );
}
