// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
var get_leaderboard_default = defineTool({
  name: "get_leaderboard",
  title: "Get leaderboard",
  description: "Get the public top-XP student leaderboard for Smart AI OMR Analysis.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Number of top students to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.rpc("get_leaderboard", { _limit: limit });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { leaderboard: data }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
function supabaseForUser(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool2({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in student's profile plus XP, level, streak, and badges.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: pErr }, { data: gam, error: gErr }] = await Promise.all([
      supabase.from("profiles").select("*").eq("id", userId).maybeSingle(),
      supabase.from("gamification").select("*").eq("id", userId).maybeSingle()
    ]);
    if (pErr || gErr) {
      return {
        content: [{ type: "text", text: (pErr ?? gErr).message }],
        isError: true
      };
    }
    const payload = { profile, gamification: gam };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-my-recent-results.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
function supabaseForUser2(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_recent_results_default = defineTool3({
  name: "get_my_recent_results",
  title: "Get my recent exam results",
  description: "List the signed-in student's most recent exam attempts (score, accuracy, subject, time).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10).describe("How many recent results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("results").select("id, sheet_title, score, max_score, accuracy, correct, total_questions, unattempted, time_spent, completed_at").eq("user_id", ctx.getUserId()).order("completed_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { results: data }
    };
  }
});

// src/lib/mcp/tools/list-my-sheets.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.101.1";
function supabaseForUser3(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_sheets_default = defineTool4({
  name: "list_my_sheets",
  title: "List my OMR sheets",
  description: "List OMR answer sheets/exam configurations owned by the signed-in student.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("sheets").select("id, title, subject, total_questions, options_per_question, marks_per_question, negative_marking, time_limit, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { sheets: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "scbqwnmclqroebxfvglr";
var mcp_default = defineMcp({
  name: "smart-ai-omr-analysis-mcp",
  title: "Smart AI OMR Analysis",
  version: "0.1.0",
  instructions: "Tools for the Smart AI OMR Analysis exam prep app. Use `get_leaderboard` for the public top-XP ranking. Authenticated tools return the signed-in student's profile (`get_my_profile`), recent exam results (`get_my_recent_results`), and saved OMR sheets (`list_my_sheets`).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_leaderboard_default, get_my_profile_default, get_my_recent_results_default, list_my_sheets_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
